language: php

php: [5.3.3, 5.3, 5.4, 5.5, hhvm]

before_script:
  - composer selfupdate
  - composer install --prefer-source

script:
  - bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
